import xgi
# import src.poisson_hypergraph as poisson_hypergraph
# from src.NMI_func import NMI
# from src.simulated_annealing import simulated_annealing_approx_likelihood, simulated_annealing_full_likelihood
import poisson_hypergraph as poisson_hypergraph
from NMI_func import NMI
from simulated_annealing import simulated_annealing_approx_likelihood, simulated_annealing_full_likelihood, SimulatedAnnealingApprox
import numpy as np
import networkx as nx
import sys
import csv

# params, should vary with job number
# theta_index = int(sys.argv[1])%5
theta_index = 0

max_considered_edge_size = int(sys.argv[1])%11 + 5

H = xgi.load_xgi_data("senate-bills")

# Violet's Code Congress Sem
party_affs = H.nodes.attrs('affiliation').asdict()
new_nodes = sorted([int(node) - 1 for node in H.nodes])
new_edges = [{int(node) - 1 for node in edge} for edge in H.edges.members()]

# get rid of edges with a larger intersection than given
temp = []
for edge in new_edges:
    if (len(edge) <= max_considered_edge_size):
        temp.append(edge)

new_edges = temp

# have to add back in, at least superficially, the nodes that are no longer considered
# otherwise, index errors
big_union = set()
for edge in new_edges:
    big_union = big_union.union(edge)

missing_nodes = set(new_nodes) - big_union
# won't affect likelihood as it cannot be generated by the scheme we are using
new_edges.append(missing_nodes)


# record dem as 0 and rep as 1 for all nodes
labels = []
for party in list(party_affs.values()):
    if party == 'Democrat':
        labels.append(0)
    if party == 'Republican':
        labels.append(1)

# create new dict using our binary labels
label_dict = dict(zip(new_nodes, labels))
sorted_label_dict = dict(sorted(label_dict.items()))

# make new hypergraph
new_H = xgi.Hypergraph(new_edges)
new_H.set_node_attributes(sorted_label_dict, name = "label")

# turn the data set into an object of the GH class (so we can perform SEM on it)
g = poisson_hypergraph.GH(new_H, [0, 1], 0, 0)







# [.43, .37, 0.001, .001, .91, .65] Violet's approx
true_thetas = [[.9, .1, .5, .25, 1, .25],
[.8, .2, .5, .25, 1, .25],
[.7, .3, .5, .25, 1, .25],
[.6, .4, .5, .25, 1, .25],
[.43, .37, 0.5, .25, .91, .65]]

true_theta = true_thetas[theta_index]

sa = SimulatedAnnealingApprox(g, true_theta)

for step_num in range(len(g.nodes)*20):
    print("step num: " + str(step_num))

    sa.step()

    with open('senate_max_edge_size' + str(max_considered_edge_size) + '.csv', 'a', newline="") as file:
        writer = csv.writer(file)
        writer.writerows([[step_num, sa.likelihoods_per_step[-1], sa.aris_per_step[-1]]])

